version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${mongoDatabase}
      - MONGO_INITDB_ROOT_USERNAME=${mongoUser}
      - MONGO_INITDB_ROOT_PASSWORD=${mongoPassword}
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - mongonet

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${mongoUser}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${mongoPassword}
    ports:
      - "8081:8081"
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
